export const products = [
  {
    _id: "2f4bbe63-3efb-4184-bc5b-be1dd4a6e395",
    title: "iPhone 9",
    description: "An apple mobile which is nothing like apple",
    price: 549,
    discountPercentage: 47.66444232602478,
    rating: 4.69,
    stock: 94,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/1/1.jpg",
      "https://i.dummyjson.com/data/products/1/2.jpg",
      "https://i.dummyjson.com/data/products/1/3.jpg",
      "https://i.dummyjson.com/data/products/1/4.jpg",
      "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
    ],
    trending: false,
    MRP: 1049,
    in_stock: true,
  },
  {
    _id: "0049dfd1-7a61-44a0-92a4-348f6be2fb07",
    title: "iPhone X",
    description:
      "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
    price: 899,
    discountPercentage: 43.77736085053158,
    rating: 4.44,
    stock: 34,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/2/1.jpg",
      "https://i.dummyjson.com/data/products/2/2.jpg",
      "https://i.dummyjson.com/data/products/2/3.jpg",
      "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
    ],
    trending: false,
    MRP: 1599,
    in_stock: true,
  },
  {
    _id: "cc00a1ae-5949-4a68-8441-4da5d38f5841",
    title: "Samsung Universe 9",
    description:
      "Samsung's new variant which goes beyond Galaxy to the Universe",
    price: 1249,
    discountPercentage: 45.026408450704224,
    rating: 4.09,
    stock: 36,
    brand: "Samsung",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
    images: ["https://i.dummyjson.com/data/products/3/1.jpg"],
    trending: false,
    MRP: 2272,
    in_stock: true,
  },
  {
    _id: "5672b68d-9e63-47b8-bd94-d7968ed122ea",
    title: "OPPOF19",
    description: "OPPO F19 is officially announced on April 2021.",
    price: 280,
    discountPercentage: 30.52109181141439,
    rating: 4.3,
    stock: 123,
    brand: "OPPO",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/4/1.jpg",
      "https://i.dummyjson.com/data/products/4/2.jpg",
      "https://i.dummyjson.com/data/products/4/3.jpg",
      "https://i.dummyjson.com/data/products/4/4.jpg",
      "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    ],
    trending: false,
    MRP: 403,
    in_stock: true,
  },
  {
    _id: "06ea8cbf-43d5-4103-87e7-341c079ed86d",
    title: "Huawei P30",
    description:
      "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
    price: 499,
    discountPercentage: 41.90919674039581,
    rating: 4.09,
    stock: 32,
    brand: "Huawei",
    category: "smartphones",
    thumbnail: "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/5/1.jpg",
      "https://i.dummyjson.com/data/products/5/2.jpg",
      "https://i.dummyjson.com/data/products/5/3.jpg",
    ],
    trending: false,
    MRP: 859,
    in_stock: true,
  },
  {
    _id: "84a7d04b-424b-4ff3-846b-9b6fdc8fb680",
    title: "MacBook Pro",
    description:
      "MacBook Pro 2021 with mini-LED display may launch between September, November",
    price: 1749,
    discountPercentage: 36.904761904761905,
    rating: 4.57,
    stock: 83,
    brand: "Apple",
    category: "laptops",
    thumbnail: "https://i.dummyjson.com/data/products/6/thumbnail.png",
    images: [
      "https://i.dummyjson.com/data/products/6/1.png",
      "https://i.dummyjson.com/data/products/6/2.jpg",
      "https://i.dummyjson.com/data/products/6/3.png",
      "https://i.dummyjson.com/data/products/6/4.jpg",
    ],
    trending: true,
    MRP: 2772,
    in_stock: true,
  },
  {
    _id: "b7e98b92-7646-4914-8dbc-ba1df51d4a3b",
    title: "Samsung Galaxy Book",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 40.01600640256102,
    rating: 4.25,
    stock: 50,
    brand: "Samsung",
    category: "laptops",
    thumbnail: "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/7/1.jpg",
      "https://i.dummyjson.com/data/products/7/2.jpg",
      "https://i.dummyjson.com/data/products/7/3.jpg",
      "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
    ],
    trending: false,
    MRP: 2499,
    in_stock: true,
  },
  {
    _id: "fa80a779-cb72-4be0-a1e1-c9a5d67dd51c",
    title: "Microsoft Surface Laptop 4",
    description:
      "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
    price: 1499,
    discountPercentage: 41.26175548589342,
    rating: 4.43,
    stock: 68,
    brand: "Microsoft Surface",
    category: "laptops",
    thumbnail: "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/8/1.jpg",
      "https://i.dummyjson.com/data/products/8/2.jpg",
      "https://i.dummyjson.com/data/products/8/3.jpg",
      "https://i.dummyjson.com/data/products/8/4.jpg",
      "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
    ],
    trending: false,
    MRP: 2552,
    in_stock: true,
  },
  {
    _id: "5c7838cd-29ef-44bb-8b5a-01dfb77b373c",
    title: "Infinix INBOOK",
    description:
      "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
    price: 1099,
    discountPercentage: 39.68166849615807,
    rating: 3.54,
    stock: 96,
    brand: "Infinix",
    category: "laptops",
    thumbnail: "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/9/1.jpg",
      "https://i.dummyjson.com/data/products/9/2.png",
      "https://i.dummyjson.com/data/products/9/3.png",
      "https://i.dummyjson.com/data/products/9/4.jpg",
      "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
    ],
    trending: false,
    MRP: 1822,
    in_stock: true,
  },
  {
    _id: "c692ded9-6443-4707-a99e-0748c17d6699",
    title: "HP Pavilion 15-DK1056WM",
    description:
      "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
    price: 1099,
    discountPercentage: 38.91050583657588,
    rating: 4.43,
    stock: 89,
    brand: "HP Pavilion",
    category: "laptops",
    thumbnail: "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
    images: [
      "https://i.dummyjson.com/data/products/10/1.jpg",
      "https://i.dummyjson.com/data/products/10/2.jpg",
      "https://i.dummyjson.com/data/products/10/3.jpg",
      "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
    ],
    trending: false,
    MRP: 1799,
    in_stock: true,
  },
  {
    _id: "28115d14-1d26-4976-a89f-7e45690edba4",
    title: "perfume Oil",
    description:
      "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil",
    price: 13,
    discountPercentage: 0,
    rating: 3.26,
    stock: 65,
    brand: "Impression of Acqua Di Gio",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/11/1.jpg",
      "https://i.dummyjson.com/data/products/11/2.jpg",
      "https://i.dummyjson.com/data/products/11/3.jpg",
      "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
    ],
    trending: false,
    MRP: 13,
    in_stock: true,
  },
  {
    _id: "4e570b38-4da6-4d92-a052-0192c9840e28",
    title: "Brown Perfume",
    description: "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
    price: 40,
    discountPercentage: 65.51724137931035,
    rating: 4,
    stock: 52,
    brand: "Royal_Mirage",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/12/1.jpg",
      "https://i.dummyjson.com/data/products/12/2.jpg",
      "https://i.dummyjson.com/data/products/12/3.png",
      "https://i.dummyjson.com/data/products/12/4.jpg",
      "https://i.dummyjson.com/data/products/12/thumbnail.jpg",
    ],
    trending: true,
    MRP: 116,
    in_stock: true,
  },
  {
    _id: "65f1bf15-ecd3-471c-85d0-7e1e5f36d0a4",
    title: "Fog Scent Xpressio Perfume",
    description:
      "Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men",
    price: 13,
    discountPercentage: 0,
    rating: 4.59,
    stock: 61,
    brand: "Fog Scent Xpressio",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/13/thumbnail.webp",
    images: [
      "https://i.dummyjson.com/data/products/13/1.jpg",
      "https://i.dummyjson.com/data/products/13/2.png",
      "https://i.dummyjson.com/data/products/13/3.jpg",
      "https://i.dummyjson.com/data/products/13/4.jpg",
      "https://i.dummyjson.com/data/products/13/thumbnail.webp",
    ],
    trending: false,
    MRP: 13,
    in_stock: false,
  },
  {
    _id: "cc88aeaf-7881-4904-902f-665adf92d951",
    title: "Non-Alcoholic Concentrated Perfume Oil",
    description:
      "Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil",
    price: 120,
    discountPercentage: 14.285714285714285,
    rating: 4.21,
    stock: 114,
    brand: "Al Munakh",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/14/1.jpg",
      "https://i.dummyjson.com/data/products/14/2.jpg",
      "https://i.dummyjson.com/data/products/14/3.jpg",
      "https://i.dummyjson.com/data/products/14/thumbnail.jpg",
    ],
    trending: false,
    MRP: 140,
    in_stock: true,
  },
  {
    _id: "ce5574e0-b1c8-46bc-8982-ca186ba80288",
    title: "Eau De Perfume Spray",
    description:
      "Genuine Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality",
    price: 30,
    discountPercentage: 43.39622641509434,
    rating: 4.7,
    stock: 105,
    brand: "Lord - Al-Rehab",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/15/1.jpg",
      "https://i.dummyjson.com/data/products/15/2.jpg",
      "https://i.dummyjson.com/data/products/15/3.jpg",
      "https://i.dummyjson.com/data/products/15/4.jpg",
      "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
    ],
    trending: false,
    MRP: 53,
    in_stock: true,
  },
  {
    _id: "266cbb10-6079-43d9-b56e-d7d9cc5574bc",
    title: "Hyaluronic Acid Serum",
    description:
      "L'OrÃ©al Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid",
    price: 19,
    discountPercentage: 73.61111111111111,
    rating: 3.83,
    stock: 110,
    brand: "L'Oreal Paris",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/16/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/16/1.png",
      "https://i.dummyjson.com/data/products/16/2.webp",
      "https://i.dummyjson.com/data/products/16/3.jpg",
      "https://i.dummyjson.com/data/products/16/4.jpg",
      "https://i.dummyjson.com/data/products/16/thumbnail.jpg",
    ],
    trending: false,
    MRP: 72,
    in_stock: true,
  },
  {
    _id: "3b977601-079d-4552-85e7-8216a221c560",
    title: "Tree Oil 30ml",
    description:
      "Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria,",
    price: 12,
    discountPercentage: 0,
    rating: 4.52,
    stock: 78,
    brand: "Hemani Tea",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/17/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/17/1.jpg",
      "https://i.dummyjson.com/data/products/17/2.jpg",
      "https://i.dummyjson.com/data/products/17/3.jpg",
      "https://i.dummyjson.com/data/products/17/thumbnail.jpg",
    ],
    trending: false,
    MRP: 12,
    in_stock: true,
  },
  {
    _id: "d46334fd-9d36-4ee6-aafb-39e7e75c53f9",
    title: "Oil Free Moisturizer 100ml",
    description:
      "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
    price: 40,
    discountPercentage: 36.507936507936506,
    rating: 4.56,
    stock: 88,
    brand: "Dermive",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/18/1.jpg",
      "https://i.dummyjson.com/data/products/18/2.jpg",
      "https://i.dummyjson.com/data/products/18/3.jpg",
      "https://i.dummyjson.com/data/products/18/4.jpg",
      "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    ],
    trending: true,
    MRP: 63,
    in_stock: true,
  },
  {
    _id: "57bb4afd-2731-40e3-9922-37c4392ebb59",
    title: "Skin Beauty Serum.",
    description:
      "Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m",
    price: 46,
    discountPercentage: 0,
    rating: 3.42,
    stock: 54,
    brand: "ROREC White Rice",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/19/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/19/1.jpg",
      "https://i.dummyjson.com/data/products/19/2.jpg",
      "https://i.dummyjson.com/data/products/19/3.png",
      "https://i.dummyjson.com/data/products/19/thumbnail.jpg",
    ],
    trending: false,
    MRP: 46,
    in_stock: true,
  },
  {
    _id: "aad2f8e6-0ff4-430f-93bc-3001b471893c",
    title: "Freckle Treatment Cream- 15gm",
    description:
      "Fair & Clear is Pakistan's only pure Freckle cream which helpsfade Freckles, Darkspots and pigments. Mercury level is 0%, so there are no side effects.",
    price: 70,
    discountPercentage: 51.048951048951054,
    rating: 4.06,
    stock: 140,
    brand: "Fair & Clear",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/20/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/20/1.jpg",
      "https://i.dummyjson.com/data/products/20/2.jpg",
      "https://i.dummyjson.com/data/products/20/3.jpg",
      "https://i.dummyjson.com/data/products/20/4.jpg",
      "https://i.dummyjson.com/data/products/20/thumbnail.jpg",
    ],
    trending: false,
    MRP: 143,
    in_stock: true,
  },
  {
    _id: "576728aa-f295-4202-8cca-eefdce60a2f3",
    title: "- Daal Masoor 500 grams",
    description: "Fine quality Branded Product Keep in a cool and dry place",
    price: 20,
    discountPercentage: 53.48837209302325,
    rating: 4.44,
    stock: 133,
    brand: "Saaf & Khaas",
    category: "groceries",
    thumbnail: "https://i.dummyjson.com/data/products/21/thumbnail.png",
    images: [
      "https://i.dummyjson.com/data/products/21/1.png",
      "https://i.dummyjson.com/data/products/21/2.jpg",
      "https://i.dummyjson.com/data/products/21/3.jpg",
    ],
    trending: false,
    MRP: 43,
    in_stock: true,
  },
  {
    _id: "66d62d45-1ffd-4fd4-a2aa-9266f4243616",
    title: "Elbow Macaroni - 400 gm",
    description: "Product details of Bake Parlor Big Elbow Macaroni - 400 gm",
    price: 14,
    discountPercentage: 0,
    rating: 3.57,
    stock: 146,
    brand: "Bake Parlor Big",
    category: "groceries",
    thumbnail: "https://i.dummyjson.com/data/products/22/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/22/1.jpg",
      "https://i.dummyjson.com/data/products/22/2.jpg",
      "https://i.dummyjson.com/data/products/22/3.jpg",
    ],
    trending: false,
    MRP: 14,
    in_stock: true,
  },
  {
    _id: "4e41db9a-8503-4a92-9adf-131907836156",
    title: "Orange Essence Food Flavou",
    description:
      "Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item",
    price: 14,
    discountPercentage: 0,
    rating: 2.85,
    stock: 26,
    brand: "Baking Food Items",
    category: "groceries",
    thumbnail: "https://i.dummyjson.com/data/products/23/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/23/1.jpg",
      "https://i.dummyjson.com/data/products/23/2.jpg",
      "https://i.dummyjson.com/data/products/23/3.jpg",
      "https://i.dummyjson.com/data/products/23/4.jpg",
      "https://i.dummyjson.com/data/products/23/thumbnail.jpg",
    ],
    trending: false,
    MRP: 14,
    in_stock: true,
  },
  {
    _id: "9fdb963e-2c2c-4ce9-b8a3-5710b5648bae",
    title: "cereals muesli fruit nuts",
    description:
      "original fauji cereal muesli 250gm box pack original fauji cereals muesli fruit nuts flakes breakfast cereal break fast faujicereals cerels cerel foji fouji",
    price: 46,
    discountPercentage: 62.295081967213115,
    rating: 3.94,
    stock: 113,
    brand: "fauji",
    category: "groceries",
    thumbnail: "https://i.dummyjson.com/data/products/24/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/24/1.jpg",
      "https://i.dummyjson.com/data/products/24/2.jpg",
      "https://i.dummyjson.com/data/products/24/3.jpg",
      "https://i.dummyjson.com/data/products/24/4.jpg",
      "https://i.dummyjson.com/data/products/24/thumbnail.jpg",
    ],
    trending: true,
    MRP: 122,
    in_stock: true,
  },
  {
    _id: "7858986e-e52e-4fac-91e4-5c4e979bcdae",
    title: "Gulab Powder 50 Gram",
    description: "Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds",
    price: 70,
    discountPercentage: 22.22222222222222,
    rating: 4.87,
    stock: 47,
    brand: "Dry Rose",
    category: "groceries",
    thumbnail: "https://i.dummyjson.com/data/products/25/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/25/1.png",
      "https://i.dummyjson.com/data/products/25/2.jpg",
      "https://i.dummyjson.com/data/products/25/3.png",
      "https://i.dummyjson.com/data/products/25/4.jpg",
      "https://i.dummyjson.com/data/products/25/thumbnail.jpg",
    ],
    trending: false,
    MRP: 90,
    in_stock: true,
  },
  {
    _id: "144765d3-c02e-4986-bf18-3d068107d192",
    title: "Plant Hanger For Home",
    description:
      "Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf",
    price: 41,
    discountPercentage: 0,
    rating: 3.08,
    stock: 0,
    brand: "Boho Decor",
    category: "home-appliances",
    thumbnail: "https://i.dummyjson.com/data/products/26/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/26/1.jpg",
      "https://i.dummyjson.com/data/products/26/2.jpg",
      "https://i.dummyjson.com/data/products/26/3.jpg",
      "https://i.dummyjson.com/data/products/26/4.jpg",
      "https://i.dummyjson.com/data/products/26/5.jpg",
      "https://i.dummyjson.com/data/products/26/thumbnail.jpg",
    ],
    trending: false,
    MRP: 41,
    in_stock: false,
  },
  {
    _id: "1cec21a9-3ff3-4b87-8a9c-d78d9564cc09",
    title: "Flying Wooden Bird",
    description:
      "Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm",
    price: 51,
    discountPercentage: 45.744680851063826,
    rating: 3.41,
    stock: 17,
    brand: "Flying Wooden",
    category: "home-appliances",
    thumbnail: "https://i.dummyjson.com/data/products/27/thumbnail.webp",
    images: [
      "https://i.dummyjson.com/data/products/27/1.jpg",
      "https://i.dummyjson.com/data/products/27/2.jpg",
      "https://i.dummyjson.com/data/products/27/3.jpg",
      "https://i.dummyjson.com/data/products/27/4.jpg",
      "https://i.dummyjson.com/data/products/27/thumbnail.webp",
    ],
    trending: false,
    MRP: 94,
    in_stock: true,
  },
  {
    _id: "30e13e2c-efe4-4810-8174-965533bc9daf",
    title: "3D Embellishment Art Lamp",
    description:
      "3D led lamp sticker Wall sticker 3d wall art light on/off button cell operated (included)",
    price: 20,
    discountPercentage: 72.6027397260274,
    rating: 4.82,
    stock: 54,
    brand: "LED Lights",
    category: "home-appliances",
    thumbnail: "https://i.dummyjson.com/data/products/28/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/28/1.jpg",
      "https://i.dummyjson.com/data/products/28/2.jpg",
      "https://i.dummyjson.com/data/products/28/3.png",
      "https://i.dummyjson.com/data/products/28/4.jpg",
      "https://i.dummyjson.com/data/products/28/thumbnail.jpg",
    ],
    trending: false,
    MRP: 73,
    in_stock: true,
  },
  {
    _id: "0447a618-6224-4525-867f-13cce41f4c75",
    title: "Handcraft Chinese style",
    description:
      "Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate",
    price: 60,
    discountPercentage: 78.57142857142857,
    rating: 4.44,
    stock: 7,
    brand: "luxury palace",
    category: "home-appliances",
    thumbnail: "https://i.dummyjson.com/data/products/29/thumbnail.webp",
    images: [
      "https://i.dummyjson.com/data/products/29/1.jpg",
      "https://i.dummyjson.com/data/products/29/2.jpg",
      "https://i.dummyjson.com/data/products/29/3.webp",
      "https://i.dummyjson.com/data/products/29/4.webp",
      "https://i.dummyjson.com/data/products/29/thumbnail.webp",
    ],
    trending: false,
    MRP: 280,
    in_stock: true,
  },
  {
    _id: "98fa4fbe-4a48-486e-b899-2631aa678dd2",
    title: "Key Holder",
    description:
      "Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality",
    price: 30,
    discountPercentage: 43.39622641509434,
    rating: 4.9,
    stock: 54,
    brand: "Golden",
    category: "home-appliances",
    thumbnail: "https://i.dummyjson.com/data/products/30/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/30/1.jpg",
      "https://i.dummyjson.com/data/products/30/2.jpg",
      "https://i.dummyjson.com/data/products/30/3.jpg",
      "https://i.dummyjson.com/data/products/30/thumbnail.jpg",
    ],
    trending: true,
    MRP: 53,
    in_stock: true,
  },
  {
    _id: "cea66e77-2bb9-4064-a686-4fa9835eb5e1",
    title: "Mornadi Velvet Bed",
    description:
      "Mornadi Velvet Bed Base with Headboard Slats Support Classic Style Bedroom Furniture Bed Set",
    price: 40,
    discountPercentage: 0,
    rating: 2.16,
    stock: 140,
    brand: "Furniture Bed Set",
    category: "home-appliances",
    thumbnail: "https://i.dummyjson.com/data/products/31/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/31/1.jpg",
      "https://i.dummyjson.com/data/products/31/2.jpg",
      "https://i.dummyjson.com/data/products/31/3.jpg",
      "https://i.dummyjson.com/data/products/31/4.jpg",
      "https://i.dummyjson.com/data/products/31/thumbnail.jpg",
    ],
    trending: false,
    MRP: 40,
    in_stock: true,
  },
  {
    _id: "d50c8cf3-e004-4a14-b23c-f0c6fc20677b",
    title: "Sofa for Coffe Cafe",
    description:
      "Ratttan Outdoor home-appliances Set Waterproof Rattan Sofa for Coffe Cafe",
    price: 50,
    discountPercentage: 59.34959349593496,
    rating: 4.74,
    stock: 30,
    brand: "Ratttan Outdoor",
    category: "home-appliances",
    thumbnail: "https://i.dummyjson.com/data/products/32/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/32/1.jpg",
      "https://i.dummyjson.com/data/products/32/2.jpg",
      "https://i.dummyjson.com/data/products/32/3.jpg",
      "https://i.dummyjson.com/data/products/32/thumbnail.jpg",
    ],
    trending: false,
    MRP: 123,
    in_stock: true,
  },
  {
    _id: "58d9c9da-3b95-452c-9332-cedc59572ba5",
    title: "3 Tier Corner Shelves",
    description:
      "3 Tier Corner Shelves | 3 PCs Wall Mount Kitchen Shelf | Floating Bedroom Shelf",
    price: 700,
    discountPercentage: 42.76369582992641,
    rating: 3.31,
    stock: 106,
    brand: "Kitchen Shelf",
    category: "home-appliances",
    thumbnail: "https://i.dummyjson.com/data/products/33/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/33/1.jpg",
      "https://i.dummyjson.com/data/products/33/2.jpg",
      "https://i.dummyjson.com/data/products/33/3.jpg",
      "https://i.dummyjson.com/data/products/33/4.jpg",
      "https://i.dummyjson.com/data/products/33/thumbnail.jpg",
    ],
    trending: false,
    MRP: 1223,
    in_stock: true,
  },
  {
    _id: "015f8f6c-c576-4f09-9dca-c1e0cdc6cbf6",
    title: "Plastic Table",
    description:
      "V﻿ery good quality plastic table for multi purpose now in reasonable price",
    price: 50,
    discountPercentage: 28.57142857142857,
    rating: 4.01,
    stock: 136,
    brand: "Multi Purpose",
    category: "home-appliances",
    thumbnail: "https://i.dummyjson.com/data/products/34/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/34/1.jpg",
      "https://i.dummyjson.com/data/products/34/2.jpg",
      "https://i.dummyjson.com/data/products/34/3.jpg",
      "https://i.dummyjson.com/data/products/34/4.jpg",
      "https://i.dummyjson.com/data/products/34/thumbnail.jpg",
    ],
    trending: false,
    MRP: 70,
    in_stock: true,
  },
  {
    _id: "cc1cdba1-588d-40e1-9b8a-fa33118022a2",
    title: "3 DOOR PORTABLE",
    description:
      "Material: Stainless Steel and Fabric Item Size: 110 cm x 45 cm x 175 cm Package Contents: 1 Storage Wardrobe",
    price: 41,
    discountPercentage: 0,
    rating: 4.06,
    stock: 68,
    brand: "AmnaMart",
    category: "home-appliances",
    thumbnail: "https://i.dummyjson.com/data/products/35/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/35/1.jpg",
      "https://i.dummyjson.com/data/products/35/2.jpg",
      "https://i.dummyjson.com/data/products/35/3.jpg",
      "https://i.dummyjson.com/data/products/35/4.jpg",
      "https://i.dummyjson.com/data/products/35/thumbnail.jpg",
    ],
    trending: false,
    MRP: 41,
    in_stock: true,
  },
  {
    _id: "f75949b6-96e2-4fb5-b67d-095f0e841310",
    title: "Sleeve Shirt Womens",
    description:
      "Cotton Solid Color Professional Wear Sleeve Shirt Womens Work Blouses Wholesale Clothing Casual Plain Custom Top OEM Customized",
    price: 90,
    discountPercentage: 51.61290322580645,
    rating: 4.26,
    stock: 39,
    brand: "Professional Wear",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/36/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/36/1.jpg",
      "https://i.dummyjson.com/data/products/36/2.webp",
      "https://i.dummyjson.com/data/products/36/3.webp",
      "https://i.dummyjson.com/data/products/36/4.jpg",
      "https://i.dummyjson.com/data/products/36/thumbnail.jpg",
    ],
    trending: true,
    MRP: 186,
    in_stock: true,
  },
  {
    _id: "20fcce77-726c-4371-acd7-ef0cd2bbcc11",
    title: "ank Tops for Womens/Girls",
    description:
      "PACK OF 3 CAMISOLES ,VERY COMFORTABLE SOFT COTTON STUFF, COMFORTABLE IN ALL FOUR SEASONS",
    price: 50,
    discountPercentage: 28.57142857142857,
    rating: 3.52,
    stock: 107,
    brand: "Soft Cotton",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/37/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/37/1.jpg",
      "https://i.dummyjson.com/data/products/37/2.jpg",
      "https://i.dummyjson.com/data/products/37/3.jpg",
      "https://i.dummyjson.com/data/products/37/4.jpg",
      "https://i.dummyjson.com/data/products/37/thumbnail.jpg",
    ],
    trending: false,
    MRP: 70,
    in_stock: true,
  },
  {
    _id: "d01cda98-d1de-4f22-ad55-e3c8cfef6450",
    title: "sublimation plain kids tank",
    description: "sublimation plain kids tank fashion wholesale",
    price: 100,
    discountPercentage: 16.666666666666664,
    rating: 3.8,
    stock: 20,
    brand: "Soft Cotton",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/38/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/38/1.png",
      "https://i.dummyjson.com/data/products/38/2.jpg",
      "https://i.dummyjson.com/data/products/38/3.jpg",
      "https://i.dummyjson.com/data/products/38/4.jpg",
    ],
    trending: false,
    MRP: 120,
    in_stock: true,
  },
  {
    _id: "59483e80-332e-4d3e-ae9b-8a4160e0c996",
    title: "Women Sweaters Wool",
    description:
      "2021 Custom Winter Fall Zebra Knit Crop Top Women Sweaters Wool Mohair Cos Customize Crew Neck Women' S Crop Top Sweater",
    price: 600,
    discountPercentage: 60.604070912672356,
    rating: 4.55,
    stock: 0,
    brand: "Top Sweater",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/39/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/39/1.jpg",
      "https://i.dummyjson.com/data/products/39/2.jpg",
      "https://i.dummyjson.com/data/products/39/3.jpg",
      "https://i.dummyjson.com/data/products/39/4.jpg",
      "https://i.dummyjson.com/data/products/39/thumbnail.jpg",
    ],
    trending: false,
    MRP: 1523,
    in_stock: false,
  },
  {
    _id: "77969c82-1e89-4f5d-9295-6673e45fbf5d",
    title: "women winter clothes",
    description:
      "women winter clothes thick fleece hoodie top with sweat pantjogger women sweatsuit set joggers pants two piece pants set",
    price: 57,
    discountPercentage: 56.15384615384615,
    rating: 3.91,
    stock: 84,
    brand: "Top Sweater",
    category: "tops",
    thumbnail: "https://i.dummyjson.com/data/products/40/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/40/1.jpg",
      "https://i.dummyjson.com/data/products/40/2.jpg",
    ],
    trending: false,
    MRP: 130,
    in_stock: true,
  },
  {
    _id: "abe0f703-ae57-4019-a98a-569078e0148e",
    title: "NIGHT SUIT",
    description: "NIGHT SUIT RED MICKY MOUSE.. For Girls. Fantastic Suits.",
    price: 55,
    discountPercentage: 26.666666666666668,
    rating: 4.65,
    stock: 21,
    brand: "RED MICKY MOUSE..",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/41/thumbnail.webp",
    images: [
      "https://i.dummyjson.com/data/products/41/1.jpg",
      "https://i.dummyjson.com/data/products/41/2.webp",
      "https://i.dummyjson.com/data/products/41/3.jpg",
      "https://i.dummyjson.com/data/products/41/4.jpg",
      "https://i.dummyjson.com/data/products/41/thumbnail.webp",
    ],
    trending: false,
    MRP: 75,
    in_stock: true,
  },
  {
    _id: "6e428d23-c18b-47a5-bfc0-45e80f7d835a",
    title: "Stiched Kurta plus trouser",
    description:
      "FABRIC: LILEIN CHEST: 21 LENGHT: 37 TROUSER: (38) :ARABIC LILEIN",
    price: 80,
    discountPercentage: 34.959349593495936,
    rating: 4.05,
    stock: 148,
    brand: "Digital Printed",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/42/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/42/1.png",
      "https://i.dummyjson.com/data/products/42/2.png",
      "https://i.dummyjson.com/data/products/42/3.png",
      "https://i.dummyjson.com/data/products/42/4.jpg",
      "https://i.dummyjson.com/data/products/42/thumbnail.jpg",
    ],
    trending: true,
    MRP: 123,
    in_stock: true,
  },
  {
    _id: "c15131b0-df7f-4776-991a-c457dec6dd9c",
    title: "frock gold printed",
    description:
      "Ghazi fabric long frock gold printed ready to wear stitched collection (G992)",
    price: 600,
    discountPercentage: 45.45454545454545,
    rating: 4.31,
    stock: 150,
    brand: "Ghazi Fabric",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/43/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/43/1.jpg",
      "https://i.dummyjson.com/data/products/43/2.jpg",
      "https://i.dummyjson.com/data/products/43/3.jpg",
      "https://i.dummyjson.com/data/products/43/4.jpg",
      "https://i.dummyjson.com/data/products/43/thumbnail.jpg",
    ],
    trending: false,
    MRP: 1100,
    in_stock: true,
  },
  {
    _id: "3eb3f7fc-f8b5-4f02-aca8-e65822dfb973",
    title: "Ladies Multicolored Dress",
    description:
      "This classy shirt for women gives you a gorgeous look on everyday wear and specially for semi-casual wears.",
    price: 79,
    discountPercentage: 48.026315789473685,
    rating: 4.03,
    stock: 2,
    brand: "Ghazi Fabric",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/44/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/44/1.jpg",
      "https://i.dummyjson.com/data/products/44/2.jpg",
      "https://i.dummyjson.com/data/products/44/3.jpg",
      "https://i.dummyjson.com/data/products/44/4.jpg",
      "https://i.dummyjson.com/data/products/44/thumbnail.jpg",
    ],
    trending: false,
    MRP: 152,
    in_stock: true,
  },
  {
    _id: "5048e417-8bfb-4ffc-94c3-0d24b6fe0879",
    title: "Malai Maxi Dress",
    description:
      "Ready to wear, Unique design according to modern standard fashion, Best fitting ,Imported stuff",
    price: 50,
    discountPercentage: 46.236559139784944,
    rating: 3.67,
    stock: 96,
    brand: "IELGY",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/45/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/45/1.jpg",
      "https://i.dummyjson.com/data/products/45/2.webp",
      "https://i.dummyjson.com/data/products/45/3.jpg",
      "https://i.dummyjson.com/data/products/45/4.jpg",
      "https://i.dummyjson.com/data/products/45/thumbnail.jpg",
    ],
    trending: false,
    MRP: 93,
    in_stock: true,
  },
  {
    _id: "5ab83c6e-5dce-4aeb-a874-2c2b41e84544",
    title: "women's shoes",
    description:
      "Close: Lace, Style with bottom: Increased inside, Sole Material: Rubber",
    price: 40,
    discountPercentage: 0,
    rating: 4.14,
    stock: 72,
    brand: "IELGY fashion",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/46/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/46/1.webp",
      "https://i.dummyjson.com/data/products/46/2.jpg",
      "https://i.dummyjson.com/data/products/46/3.jpg",
      "https://i.dummyjson.com/data/products/46/4.jpg",
      "https://i.dummyjson.com/data/products/46/thumbnail.jpg",
    ],
    trending: false,
    MRP: 40,
    in_stock: true,
  },
  {
    _id: "27e407dc-0ea0-488e-a524-042c9fc25c77",
    title: "Sneaker shoes",
    description:
      "Synthetic Leather Casual Sneaker shoes for Women/girls Sneakers For Women",
    price: 120,
    discountPercentage: 14.285714285714285,
    rating: 4.19,
    stock: 50,
    brand: "Synthetic Leather",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/47/thumbnail.jpeg",
    images: [
      "https://i.dummyjson.com/data/products/47/1.jpg",
      "https://i.dummyjson.com/data/products/47/2.jpg",
      "https://i.dummyjson.com/data/products/47/3.jpg",
      "https://i.dummyjson.com/data/products/47/thumbnail.jpeg",
    ],
    trending: false,
    MRP: 140,
    in_stock: true,
  },
  {
    _id: "e80af8b3-a2d0-411c-b27d-3d4878ee0816",
    title: "Women Strip Heel",
    description:
      "Features: Flip-flops, Mid Heel, Comfortable, Striped Heel, Antiskid, Striped",
    price: 40,
    discountPercentage: 65.51724137931035,
    rating: 4.02,
    stock: 25,
    brand: "Sandals Flip Flops",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/48/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/48/1.jpg",
      "https://i.dummyjson.com/data/products/48/2.jpg",
      "https://i.dummyjson.com/data/products/48/3.jpg",
      "https://i.dummyjson.com/data/products/48/4.jpg",
      "https://i.dummyjson.com/data/products/48/thumbnail.jpg",
    ],
    trending: true,
    MRP: 116,
    in_stock: true,
  },
  {
    _id: "e5fd67b4-2990-400f-a8e9-8784dc66e496",
    title: "Chappals & Shoe Ladies Metallic",
    description:
      "Womens Chappals & Shoe Ladies Metallic Tong Thong Sandal Flat Summer 2020 Maasai Sandals",
    price: 23,
    discountPercentage: 0,
    rating: 4.12,
    stock: 107,
    brand: "Maasai Sandals",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/49/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/49/1.jpg",
      "https://i.dummyjson.com/data/products/49/2.jpg",
      "https://i.dummyjson.com/data/products/49/3.webp",
      "https://i.dummyjson.com/data/products/49/thumbnail.jpg",
    ],
    trending: false,
    MRP: 23,
    in_stock: true,
  },
  {
    _id: "dda01568-1219-46d6-9c84-c97dae5b04a2",
    title: "Women Shoes",
    description:
      "2020 New Arrivals Genuine Leather Fashion Trend Platform Summer Women Shoes",
    price: 36,
    discountPercentage: 0,
    rating: 4.33,
    stock: 46,
    brand: "Arrivals Genuine",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/50/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/50/1.jpeg",
      "https://i.dummyjson.com/data/products/50/2.jpg",
      "https://i.dummyjson.com/data/products/50/3.jpg",
    ],
    trending: false,
    MRP: 36,
    in_stock: true,
  },
  {
    _id: "1c6e46ff-8dc6-4a48-8a9d-170d71f751c6",
    title: "half sleeves T shirts",
    description:
      "Many store is creating new designs and trend every month and every year. Daraz.pk have a beautiful range of men fashion brands",
    price: 23,
    discountPercentage: 50,
    rating: 4.26,
    stock: 132,
    brand: "Vintage Apparel",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/51/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/51/1.png",
      "https://i.dummyjson.com/data/products/51/2.jpg",
      "https://i.dummyjson.com/data/products/51/3.jpg",
      "https://i.dummyjson.com/data/products/51/thumbnail.jpg",
    ],
    trending: false,
    MRP: 46,
    in_stock: true,
  },
  {
    _id: "708c8cfd-89e4-46e1-b460-8f39b79775ca",
    title: "FREE FIRE T Shirt",
    description:
      "quality and professional print - It doesn't just look high quality, it is high quality.",
    price: 10,
    discountPercentage: 84.12698412698413,
    rating: 1.52,
    stock: 0,
    brand: "FREE FIRE",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/52/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/52/1.png",
      "https://i.dummyjson.com/data/products/52/2.png",
      "https://i.dummyjson.com/data/products/52/3.jpg",
      "https://i.dummyjson.com/data/products/52/4.jpg",
      "https://i.dummyjson.com/data/products/52/thumbnail.jpg",
    ],
    trending: false,
    MRP: 63,
    in_stock: false,
  },
  {
    _id: "69f762b6-5e6d-41eb-b980-545532fc895b",
    title: "printed high quality T shirts",
    description: "Brand: vintage Apparel ,Export quality",
    price: 35,
    discountPercentage: 0,
    rating: 2.89,
    stock: 6,
    brand: "Vintage Apparel",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/53/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/53/1.webp",
      "https://i.dummyjson.com/data/products/53/2.jpg",
      "https://i.dummyjson.com/data/products/53/3.jpg",
      "https://i.dummyjson.com/data/products/53/4.jpg",
      "https://i.dummyjson.com/data/products/53/thumbnail.jpg",
    ],
    trending: false,
    MRP: 35,
    in_stock: true,
  },
  {
    _id: "500dc523-f180-44e7-86c2-38e1a28de686",
    title: "Pubg Printed Graphic T-Shirt",
    description:
      "Product Description Features: 100% Ultra soft Polyester Jersey. Vibrant & colorful printing on front. Feels soft as cotton without ever cracking",
    price: 46,
    discountPercentage: 33.33333333333333,
    rating: 3.62,
    stock: 136,
    brand: "The Warehouse",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/54/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/54/1.jpg",
      "https://i.dummyjson.com/data/products/54/2.jpg",
      "https://i.dummyjson.com/data/products/54/3.jpg",
      "https://i.dummyjson.com/data/products/54/4.jpg",
      "https://i.dummyjson.com/data/products/54/thumbnail.jpg",
    ],
    trending: true,
    MRP: 69,
    in_stock: true,
  },
  {
    _id: "f21cc82c-8738-4aaa-a117-c0651b668198",
    title: "Money Heist Printed Summer T Shirts",
    description: "Fabric Jercy, Size: M & L Wear Stylish Dual Stiched",
    price: 66,
    discountPercentage: 23.25581395348837,
    rating: 3.9,
    stock: 122,
    brand: "The Warehouse",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/55/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/55/1.jpg",
      "https://i.dummyjson.com/data/products/55/2.webp",
      "https://i.dummyjson.com/data/products/55/3.jpg",
      "https://i.dummyjson.com/data/products/55/4.jpg",
      "https://i.dummyjson.com/data/products/55/thumbnail.jpg",
    ],
    trending: false,
    MRP: 86,
    in_stock: true,
  },
  {
    _id: "bb7cb4a7-a8e8-4717-96f0-a5d473deaa2d",
    title: "Sneakers Joggers Shoes",
    description:
      "Gender: Men , Colors: Same as DisplayedCondition: 100% Brand New",
    price: 40,
    discountPercentage: 56.98924731182796,
    rating: 3.38,
    stock: 6,
    brand: "Sneakers",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/56/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/56/1.jpg",
      "https://i.dummyjson.com/data/products/56/2.jpg",
      "https://i.dummyjson.com/data/products/56/3.jpg",
      "https://i.dummyjson.com/data/products/56/4.jpg",
      "https://i.dummyjson.com/data/products/56/5.jpg",
      "https://i.dummyjson.com/data/products/56/thumbnail.jpg",
    ],
    trending: false,
    MRP: 93,
    in_stock: true,
  },
  {
    _id: "babbafc4-beb5-49c0-b6cb-5824a79d5953",
    title: "Loafers for men",
    description:
      "Men Shoes - Loafers for men - Rubber Shoes - Nylon Shoes - Shoes for men - Moccassion - Pure Nylon (Rubber) Expot Quality.",
    price: 47,
    discountPercentage: 32.857142857142854,
    rating: 3.91,
    stock: 20,
    brand: "Rubber",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/57/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/57/1.jpg",
      "https://i.dummyjson.com/data/products/57/2.jpg",
      "https://i.dummyjson.com/data/products/57/3.jpg",
      "https://i.dummyjson.com/data/products/57/4.jpg",
      "https://i.dummyjson.com/data/products/57/thumbnail.jpg",
    ],
    trending: false,
    MRP: 70,
    in_stock: true,
  },
  {
    _id: "c40a343a-f836-4962-b95f-037d73b6e118",
    title: "formal offices shoes",
    description:
      "Pattern Type: Solid, Material: PU, Toe Shape: Pointed Toe ,Outsole Material: Rubber",
    price: 57,
    discountPercentage: 25.97402597402597,
    rating: 4.41,
    stock: 68,
    brand: "The Warehouse",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/58/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/58/1.jpg",
      "https://i.dummyjson.com/data/products/58/2.jpg",
      "https://i.dummyjson.com/data/products/58/3.jpg",
      "https://i.dummyjson.com/data/products/58/4.jpg",
      "https://i.dummyjson.com/data/products/58/thumbnail.jpg",
    ],
    trending: false,
    MRP: 77,
    in_stock: true,
  },
  {
    _id: "83a43fc3-6dba-4742-bf8f-ff1b136963c0",
    title: "Spring and summershoes",
    description:
      "Comfortable stretch cloth, lightweight body; ,rubber sole, anti-skid wear;",
    price: 20,
    discountPercentage: 0,
    rating: 4.33,
    stock: 137,
    brand: "Sneakers",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/59/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/59/1.jpg",
      "https://i.dummyjson.com/data/products/59/2.jpg",
      "https://i.dummyjson.com/data/products/59/3.jpg",
      "https://i.dummyjson.com/data/products/59/4.jpg",
      "https://i.dummyjson.com/data/products/59/thumbnail.jpg",
    ],
    trending: false,
    MRP: 20,
    in_stock: true,
  },
  {
    _id: "fccd0d0f-af89-4a67-9b6b-81f96ac4e163",
    title: "Stylish Casual Jeans Shoes",
    description:
      "High Quality ,Stylish design ,Comfortable wear ,FAshion ,Durable",
    price: 58,
    discountPercentage: 62.33766233766234,
    rating: 4.55,
    stock: 129,
    brand: "Sneakers",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/60/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/60/1.jpg",
      "https://i.dummyjson.com/data/products/60/2.jpg",
      "https://i.dummyjson.com/data/products/60/3.jpg",
      "https://i.dummyjson.com/data/products/60/thumbnail.jpg",
    ],
    trending: true,
    MRP: 154,
    in_stock: true,
  },
  {
    _id: "5b513758-156f-43d4-a314-3d8ad9db7230",
    title: "Leather Straps Wristwatch",
    description: "Style:Sport ,Clasp:Buckles ,Water Resistance Depth:3Bar",
    price: 120,
    discountPercentage: 14.285714285714285,
    rating: 4.63,
    stock: 91,
    brand: "Naviforce",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/61/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/61/1.jpg",
      "https://i.dummyjson.com/data/products/61/2.png",
      "https://i.dummyjson.com/data/products/61/3.jpg",
    ],
    trending: false,
    MRP: 140,
    in_stock: true,
  },
  {
    _id: "eef91ccc-be3c-433c-b372-cb394c0ae624",
    title: "Waterproof Leather Brand Watch",
    description:
      "Watch Crown With Environmental IPS Bronze Electroplating; Display system of 12 hours",
    price: 46,
    discountPercentage: 0,
    rating: 4.05,
    stock: 95,
    brand: "SKMEI 9117",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/62/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/62/1.jpg",
      "https://i.dummyjson.com/data/products/62/2.jpg",
    ],
    trending: false,
    MRP: 46,
    in_stock: true,
  },
  {
    _id: "1904334f-94db-4726-b2bc-e33a2cb29e74",
    title: "Royal Blue Premium Watch",
    description:
      "Men Silver Chain Royal Blue Premium Watch Latest Analog Watch",
    price: 50,
    discountPercentage: 46.236559139784944,
    rating: 2.89,
    stock: 142,
    brand: "SKMEI 9117",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/63/thumbnail.webp",
    images: [
      "https://i.dummyjson.com/data/products/63/1.jpg",
      "https://i.dummyjson.com/data/products/63/2.jpg",
      "https://i.dummyjson.com/data/products/63/3.png",
      "https://i.dummyjson.com/data/products/63/4.jpeg",
    ],
    trending: false,
    MRP: 93,
    in_stock: true,
  },
  {
    _id: "c026eb0c-770b-49a2-be5e-3da3b470b35f",
    title: "Leather Strap Skeleton Watch",
    description:
      "Leather Strap Skeleton Watch for Men - Stylish and Latest Design",
    price: 46,
    discountPercentage: 53.535353535353536,
    rating: 3.98,
    stock: 61,
    brand: "Strap Skeleton",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/64/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/64/1.jpg",
      "https://i.dummyjson.com/data/products/64/2.webp",
      "https://i.dummyjson.com/data/products/64/3.jpg",
      "https://i.dummyjson.com/data/products/64/thumbnail.jpg",
    ],
    trending: false,
    MRP: 99,
    in_stock: true,
  },
  {
    _id: "afac6c8f-8f74-4f40-bae0-6690b0656b7b",
    title: "Stainless Steel Wrist Watch",
    description:
      "Stylish Watch For Man (Luxury) Classy Men's Stainless Steel Wrist Watch - Box Packed",
    price: 47,
    discountPercentage: 0,
    rating: 2.79,
    stock: 0,
    brand: "Stainless",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/65/thumbnail.webp",
    images: [
      "https://i.dummyjson.com/data/products/65/1.jpg",
      "https://i.dummyjson.com/data/products/65/2.webp",
      "https://i.dummyjson.com/data/products/65/3.jpg",
      "https://i.dummyjson.com/data/products/65/4.webp",
      "https://i.dummyjson.com/data/products/65/thumbnail.webp",
    ],
    trending: false,
    MRP: 47,
    in_stock: false,
  },
  {
    _id: "c39fca13-b927-48cc-888e-aadfbf54d802",
    title: "Steel Analog Couple Watches",
    description: "Elegant design, Stylish ,Unique & Trendy,Comfortable wear",
    price: 35,
    discountPercentage: 39.6551724137931,
    rating: 3.79,
    stock: 24,
    brand: "Eastern Watches",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/66/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/66/1.jpg",
      "https://i.dummyjson.com/data/products/66/2.jpg",
      "https://i.dummyjson.com/data/products/66/3.jpg",
      "https://i.dummyjson.com/data/products/66/4.JPG",
      "https://i.dummyjson.com/data/products/66/thumbnail.jpg",
    ],
    trending: true,
    MRP: 58,
    in_stock: true,
  },
  {
    _id: "7fd54ae1-f0a9-41e7-8aa9-e36204b7624e",
    title: "Fashion Magnetic Wrist Watch",
    description:
      "Buy this awesome The product is originally manufactured by the company and it's a top selling product with a very reasonable",
    price: 60,
    discountPercentage: 50.413223140495866,
    rating: 4.03,
    stock: 46,
    brand: "Eastern Watches",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/67/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/67/1.jpg",
      "https://i.dummyjson.com/data/products/67/2.jpg",
      "https://i.dummyjson.com/data/products/67/3.jpg",
      "https://i.dummyjson.com/data/products/67/4.jpg",
      "https://i.dummyjson.com/data/products/67/thumbnail.jpg",
    ],
    trending: false,
    MRP: 121,
    in_stock: true,
  },
  {
    _id: "e5b7bfcc-a560-44ab-ac47-598e2378a4a3",
    title: "Stylish Luxury Digital Watch",
    description:
      "Stylish Luxury Digital Watch For Girls / Women - Led Smart Ladies Watches For Girls",
    price: 57,
    discountPercentage: 56.15384615384615,
    rating: 3.55,
    stock: 77,
    brand: "Luxury Digital",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/68/thumbnail.webp",
    images: [
      "https://i.dummyjson.com/data/products/68/1.jpg",
      "https://i.dummyjson.com/data/products/68/2.jpg",
    ],
    trending: false,
    MRP: 130,
    in_stock: true,
  },
  {
    _id: "150c2c69-bda9-4188-aee6-ef7a62528297",
    title: "Golden Watch Pearls Bracelet Watch",
    description:
      "Product details of Golden Watch Pearls Bracelet Watch For Girls - Golden Chain Ladies Bracelate Watch for Women",
    price: 47,
    discountPercentage: 32.857142857142854,
    rating: 3.77,
    stock: 89,
    brand: "Watch Pearls",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/69/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/69/1.jpg",
      "https://i.dummyjson.com/data/products/69/2.jpg",
      "https://i.dummyjson.com/data/products/69/3.webp",
      "https://i.dummyjson.com/data/products/69/4.jpg",
      "https://i.dummyjson.com/data/products/69/thumbnail.jpg",
    ],
    trending: false,
    MRP: 70,
    in_stock: true,
  },
  {
    _id: "cbdd8dee-a9fe-4572-92cd-e8fb4daa896a",
    title: "Stainless Steel Women",
    description:
      "Fashion Skmei 1830 Shell Dial Stainless Steel Women Wrist Watch Lady Bracelet Watch Quartz Watches Ladies",
    price: 35,
    discountPercentage: 0,
    rating: 2.08,
    stock: 111,
    brand: "Bracelet",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/70/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/70/1.jpg",
      "https://i.dummyjson.com/data/products/70/2.jpg",
      "https://i.dummyjson.com/data/products/70/thumbnail.jpg",
    ],
    trending: false,
    MRP: 35,
    in_stock: true,
  },
  {
    _id: "4a14e813-d812-40a0-905c-5c327561c92e",
    title: "Women Shoulder Bags",
    description:
      "LouisWill Women Shoulder Bags Long Clutches Cross Body Bags Phone Bags PU Leather Hand Bags Large Capacity Card Holders Zipper Coin Purses Fashion Crossbody Bags for Girls Ladies",
    price: 46,
    discountPercentage: 0,
    rating: 3.71,
    stock: 17,
    brand: "LouisWill",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/71/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/71/1.jpg",
      "https://i.dummyjson.com/data/products/71/2.jpg",
      "https://i.dummyjson.com/data/products/71/3.webp",
      "https://i.dummyjson.com/data/products/71/thumbnail.jpg",
    ],
    trending: false,
    MRP: 46,
    in_stock: true,
  },
  {
    _id: "cc7f4a0d-f6f3-4899-8979-43f395f1439b",
    title: "Handbag For Girls",
    description:
      "This fashion is designed to add a charming effect to your casual outfit. This Bag is made of synthetic leather.",
    price: 23,
    discountPercentage: 76.76767676767676,
    rating: 2.91,
    stock: 27,
    brand: "LouisWill",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/72/thumbnail.webp",
    images: [
      "https://i.dummyjson.com/data/products/72/1.jpg",
      "https://i.dummyjson.com/data/products/72/2.png",
      "https://i.dummyjson.com/data/products/72/3.webp",
      "https://i.dummyjson.com/data/products/72/4.jpg",
      "https://i.dummyjson.com/data/products/72/thumbnail.webp",
    ],
    trending: true,
    MRP: 99,
    in_stock: true,
  },
  {
    _id: "cc335a75-5b76-4611-af3d-cd48e2fc9d39",
    title: "Fancy hand clutch",
    description:
      "This fashion is designed to add a charming effect to your casual outfit. This Bag is made of synthetic leather.",
    price: 44,
    discountPercentage: 0,
    rating: 4.18,
    stock: 101,
    brand: "Bracelet",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/73/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/73/1.jpg",
      "https://i.dummyjson.com/data/products/73/2.webp",
      "https://i.dummyjson.com/data/products/73/3.jpg",
      "https://i.dummyjson.com/data/products/73/thumbnail.jpg",
    ],
    trending: false,
    MRP: 44,
    in_stock: true,
  },
  {
    _id: "cf187ecf-3ab2-4c8b-88c7-7fab5ba523b1",
    title: "Leather Hand Bag",
    description:
      "It features an attractive design that makes it a must have accessory in your collection. We sell different kind of bags for boys, kids, women, girls and also for unisex.",
    price: 57,
    discountPercentage: 25.97402597402597,
    rating: 4.01,
    stock: 43,
    brand: "Copenhagen Luxe",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/74/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/74/1.jpg",
      "https://i.dummyjson.com/data/products/74/2.jpg",
      "https://i.dummyjson.com/data/products/74/3.jpg",
      "https://i.dummyjson.com/data/products/74/4.jpg",
      "https://i.dummyjson.com/data/products/74/thumbnail.jpg",
    ],
    trending: false,
    MRP: 77,
    in_stock: true,
  },
  {
    _id: "8f95dabb-b002-466f-a2b2-4a784125aedd",
    title: "Seven Pocket Women Bag",
    description:
      "Seven Pocket Women Bag Handbags Lady Shoulder Crossbody Bag Female Purse Seven Pocket Bag",
    price: 68,
    discountPercentage: 38.73873873873874,
    rating: 3.93,
    stock: 13,
    brand: "Steal Frame",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/75/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/75/1.jpg",
      "https://i.dummyjson.com/data/products/75/2.jpg",
      "https://i.dummyjson.com/data/products/75/3.jpg",
      "https://i.dummyjson.com/data/products/75/thumbnail.jpg",
    ],
    trending: false,
    MRP: 111,
    in_stock: true,
  },
  {
    _id: "5df6a4a7-37fc-420e-9baf-7ddaaa9b32a2",
    title: "Silver Ring Set Women",
    description:
      "Jewelry Type:RingsCertificate Type:NonePlating:Silver PlatedShapeattern:noneStyle:CLASSICReligious",
    price: 70,
    discountPercentage: 51.048951048951054,
    rating: 3.61,
    stock: 51,
    brand: "Darojay",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/76/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/76/1.jpg",
      "https://i.dummyjson.com/data/products/76/2.jpg",
      "https://i.dummyjson.com/data/products/76/thumbnail.jpg",
    ],
    trending: false,
    MRP: 143,
    in_stock: true,
  },
  {
    _id: "7f345076-d347-40fb-9acd-c7d13540a80f",
    title: "Rose Ring",
    description:
      "Brand: The Greetings Flower Colour: RedRing Colour: GoldenSize: Adjustable",
    price: 100,
    discountPercentage: 54.54545454545454,
    rating: 1.21,
    stock: 149,
    brand: "Copenhagen Luxe",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/77/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/77/1.jpg",
      "https://i.dummyjson.com/data/products/77/2.jpg",
      "https://i.dummyjson.com/data/products/77/3.jpg",
      "https://i.dummyjson.com/data/products/77/thumbnail.jpg",
    ],
    trending: false,
    MRP: 220,
    in_stock: true,
  },
  {
    _id: "5d3afae0-b30b-4e3f-90e7-7c4b78c5724a",
    title: "Rhinestone Korean Style Open Rings",
    description:
      "Fashion Jewellery 3Pcs Adjustable Pearl Rhinestone Korean Style Open Rings For Women",
    price: 30,
    discountPercentage: 43.39622641509434,
    rating: 3.69,
    stock: 0,
    brand: "Fashion Jewellery",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/78/thumbnail.jpg",
    images: ["https://i.dummyjson.com/data/products/78/thumbnail.jpg"],
    trending: true,
    MRP: 53,
    in_stock: false,
  },
  {
    _id: "f88d2190-6a05-4cc9-8bea-0eaac043c820",
    title: "Elegant Female Pearl Earrings",
    description:
      "Elegant Female Pearl Earrings Set Zircon Pearl Earings Women Party Accessories 9 Pairs/Set",
    price: 30,
    discountPercentage: 0,
    rating: 4.74,
    stock: 16,
    brand: "Fashion Jewellery",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/79/thumbnail.jpg",
    images: ["https://i.dummyjson.com/data/products/79/1.jpg"],
    trending: false,
    MRP: 30,
    in_stock: true,
  },
  {
    _id: "0e7311a1-f792-4757-bc14-525c79da8e6a",
    title: "Chain Pin Tassel Earrings",
    description:
      "Pair Of Ear Cuff Butterfly Long Chain Pin Tassel Earrings - Silver ( Long Life Quality Product)",
    price: 45,
    discountPercentage: 54.08163265306123,
    rating: 4.59,
    stock: 9,
    brand: "Cuff Butterfly",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/80/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/80/1.jpg",
      "https://i.dummyjson.com/data/products/80/2.jpg",
      "https://i.dummyjson.com/data/products/80/3.png",
      "https://i.dummyjson.com/data/products/80/4.jpg",
      "https://i.dummyjson.com/data/products/80/thumbnail.jpg",
    ],
    trending: false,
    MRP: 98,
    in_stock: true,
  },
  {
    _id: "81151013-9260-4757-b4d9-3de54c9cf0c4",
    title: "Round Silver Frame Sun Glasses",
    description:
      "A pair of fashion can protect your eyes from being hurt. For car driving, vacation travel, outdoor activities, social gatherings,",
    price: 19,
    discountPercentage: 54.761904761904766,
    rating: 3.94,
    stock: 78,
    brand: "Designer Sun Glasses",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/81/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/81/1.jpg",
      "https://i.dummyjson.com/data/products/81/2.jpg",
      "https://i.dummyjson.com/data/products/81/3.jpg",
      "https://i.dummyjson.com/data/products/81/4.webp",
      "https://i.dummyjson.com/data/products/81/thumbnail.jpg",
    ],
    trending: false,
    MRP: 42,
    in_stock: true,
  },
  {
    _id: "f3d89726-7fd4-4599-9fe3-a133710a1e00",
    title: "Kabir Singh Square Sunglass",
    description:
      "Orignal Metal Kabir Singh design 2020 Sunglasses Men Brand Designer Sun Glasses Kabir Singh Square Sunglass",
    price: 50,
    discountPercentage: 28.57142857142857,
    rating: 3.62,
    stock: 78,
    brand: "Designer Sun Glasses",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/82/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/82/1.jpg",
      "https://i.dummyjson.com/data/products/82/2.webp",
      "https://i.dummyjson.com/data/products/82/3.jpg",
      "https://i.dummyjson.com/data/products/82/4.jpg",
      "https://i.dummyjson.com/data/products/82/thumbnail.jpg",
    ],
    trending: false,
    MRP: 70,
    in_stock: true,
  },
  {
    _id: "d419bd86-0666-4a5f-b12b-b9c48490a447",
    title: "Wiley X Night Vision Yellow Glasses",
    description:
      "Wiley X Night Vision Yellow Glasses for Riders - Night Vision Anti Fog Driving Glasses - Free Night Glass Cover - Shield Eyes From Dust and Virus- For Night Sport Matches",
    price: 30,
    discountPercentage: 0,
    rating: 3.97,
    stock: 115,
    brand: "mastar watch",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/83/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/83/1.jpg",
      "https://i.dummyjson.com/data/products/83/2.jpg",
      "https://i.dummyjson.com/data/products/83/3.jpg",
      "https://i.dummyjson.com/data/products/83/4.jpg",
      "https://i.dummyjson.com/data/products/83/thumbnail.jpg",
    ],
    trending: false,
    MRP: 30,
    in_stock: true,
  },
  {
    _id: "5bde7845-a2f4-4a64-8b86-4ddceaa9efaf",
    title: "Square Sunglasses",
    description:
      "Fashion Oversized Square Sunglasses Retro Gradient Big Frame Sunglasses For Women One Piece Gafas Shade Mirror Clear Lens 17059",
    price: 28,
    discountPercentage: 73.07692307692307,
    rating: 3.64,
    stock: 64,
    brand: "mastar watch",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/84/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/84/1.jpg",
      "https://i.dummyjson.com/data/products/84/2.jpg",
      "https://i.dummyjson.com/data/products/84/thumbnail.jpg",
    ],
    trending: true,
    MRP: 104,
    in_stock: true,
  },
  {
    _id: "dd0266e1-90fd-4dfe-a7c8-559679ac9976",
    title: "LouisWill Men Sunglasses",
    description:
      "LouisWill Men Sunglasses Polarized Sunglasses UV400 Sunglasses Day Night Dual Use Safety Driving Night Vision Eyewear AL-MG Frame Sun Glasses with Free Box for Drivers",
    price: 50,
    discountPercentage: 28.57142857142857,
    rating: 4.98,
    stock: 92,
    brand: "LouisWill",
    category: "fashion",
    thumbnail: "https://i.dummyjson.com/data/products/85/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/85/1.jpg",
      "https://i.dummyjson.com/data/products/85/2.jpg",
      "https://i.dummyjson.com/data/products/85/thumbnail.jpg",
    ],
    trending: false,
    MRP: 70,
    in_stock: true,
  },
  {
    _id: "dd1211c0-7873-40a6-9edf-9f2a89ffe45a",
    title: "Bluetooth Aux",
    description:
      "Bluetooth Aux Bluetooth Car Aux Car Bluetooth Transmitter Aux Audio Receiver Handfree Car Bluetooth Music Receiver Universal 3.5mm Streaming A2DP Wireless Auto AUX Audio Adapter With Mic For Phone MP3",
    price: 25,
    discountPercentage: 0,
    rating: 4.57,
    stock: 22,
    brand: "Car Aux",
    category: "automotivevehicle",
    thumbnail: "https://i.dummyjson.com/data/products/86/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/86/1.jpg",
      "https://i.dummyjson.com/data/products/86/2.webp",
      "https://i.dummyjson.com/data/products/86/3.jpg",
      "https://i.dummyjson.com/data/products/86/4.jpg",
      "https://i.dummyjson.com/data/products/86/thumbnail.jpg",
    ],
    trending: false,
    MRP: 25,
    in_stock: true,
  },
  {
    _id: "e5be10a4-f6da-4e1c-bc36-363b77480b2d",
    title: "t Temperature Controller Incubator Controller",
    description:
      "Both Heat and Cool Purpose, Temperature control range; -50 to +110, Temperature measurement accuracy; 0.1, Control accuracy; 0.1",
    price: 40,
    discountPercentage: 36.507936507936506,
    rating: 3.54,
    stock: 37,
    brand: "W1209 DC12V",
    category: "automotivevehicle",
    thumbnail: "https://i.dummyjson.com/data/products/87/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/87/1.jpg",
      "https://i.dummyjson.com/data/products/87/2.jpg",
      "https://i.dummyjson.com/data/products/87/3.jpg",
      "https://i.dummyjson.com/data/products/87/4.jpg",
      "https://i.dummyjson.com/data/products/87/thumbnail.jpg",
    ],
    trending: false,
    MRP: 63,
    in_stock: true,
  },
  {
    _id: "b8c0c0dd-d9b2-44d9-a903-aa0be9191c33",
    title: "TC Reusable Silicone Magic Washing Gloves",
    description:
      "TC Reusable Silicone Magic Washing Gloves with Scrubber, Cleaning Brush Scrubber Gloves Heat Resistant Pair for Cleaning of Kitchen, Dishes, Vegetables and Fruits, Bathroom, Car Wash, Pet Care and Multipurpose",
    price: 29,
    discountPercentage: 64.63414634146342,
    rating: 2.98,
    stock: 42,
    brand: "TC Reusable",
    category: "automotivevehicle",
    thumbnail: "https://i.dummyjson.com/data/products/88/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/88/1.jpg",
      "https://i.dummyjson.com/data/products/88/2.jpg",
      "https://i.dummyjson.com/data/products/88/3.jpg",
      "https://i.dummyjson.com/data/products/88/4.webp",
      "https://i.dummyjson.com/data/products/88/thumbnail.jpg",
    ],
    trending: false,
    MRP: 82,
    in_stock: true,
  },
  {
    _id: "61211a6d-1de6-4e57-a702-87aef3d7d035",
    title: "Qualcomm original Car Charger",
    description:
      "best Quality CHarger , Highly Recommended to all best Quality CHarger , Highly Recommended to all",
    price: 40,
    discountPercentage: 0,
    rating: 1.2,
    stock: 79,
    brand: "TC Reusable",
    category: "automotivevehicle",
    thumbnail: "https://i.dummyjson.com/data/products/89/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/89/1.jpg",
      "https://i.dummyjson.com/data/products/89/2.jpg",
      "https://i.dummyjson.com/data/products/89/3.jpg",
      "https://i.dummyjson.com/data/products/89/4.jpg",
      "https://i.dummyjson.com/data/products/89/thumbnail.jpg",
    ],
    trending: false,
    MRP: 40,
    in_stock: true,
  },
  {
    _id: "b38a24c7-5304-4bad-849d-a0c28e3afd5f",
    title: "Cycle Bike Glow",
    description:
      "Universal fitment and easy to install no special wires, can be easily installed and removed. Fits most standard tyre air stem valves of road, mountain bicycles, motocycles and cars.Bright led will turn on w",
    price: 35,
    discountPercentage: 39.6551724137931,
    rating: 4.1,
    stock: 63,
    brand: "Neon LED Light",
    category: "automotivevehicle",
    thumbnail: "https://i.dummyjson.com/data/products/90/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/90/1.jpg",
      "https://i.dummyjson.com/data/products/90/2.jpg",
      "https://i.dummyjson.com/data/products/90/3.jpg",
      "https://i.dummyjson.com/data/products/90/4.jpg",
      "https://i.dummyjson.com/data/products/90/thumbnail.jpg",
    ],
    trending: true,
    MRP: 58,
    in_stock: true,
  },
  {
    _id: "7a2f479a-922c-4bc1-9cd3-6599fcff6aae",
    title: "Black Motorbike",
    description:
      "Engine Type:Wet sump, Single Cylinder, Four Stroke, Two Valves, Air Cooled with SOHC (Single Over Head Cam) Chain Drive Bore & Stroke:47.0 x 49.5 MM",
    price: 569,
    discountPercentage: 46.77268475210477,
    rating: 4.04,
    stock: 115,
    brand: "METRO 70cc Motorcycle - MR70",
    category: "automotivevehicle",
    thumbnail: "https://i.dummyjson.com/data/products/91/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/91/1.jpg",
      "https://i.dummyjson.com/data/products/91/2.jpg",
      "https://i.dummyjson.com/data/products/91/3.jpg",
      "https://i.dummyjson.com/data/products/91/4.jpg",
      "https://i.dummyjson.com/data/products/91/thumbnail.jpg",
    ],
    trending: false,
    MRP: 1069,
    in_stock: true,
  },
  {
    _id: "ec83e197-b79d-4a63-820b-8eea56617459",
    title: "HOT SALE IN EUROPE electric racing motorcycle",
    description:
      "HOT SALE IN EUROPE electric racing motorcycle electric motorcycle for sale adult electric motorcycles",
    price: 920,
    discountPercentage: 45.00896592946802,
    rating: 2.19,
    stock: 22,
    brand: "BRAVE BULL",
    category: "automotivevehicle",
    thumbnail: "https://i.dummyjson.com/data/products/92/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/92/1.jpg",
      "https://i.dummyjson.com/data/products/92/2.jpg",
      "https://i.dummyjson.com/data/products/92/3.jpg",
      "https://i.dummyjson.com/data/products/92/4.jpg",
    ],
    trending: false,
    MRP: 1673,
    in_stock: true,
  },
  {
    _id: "1d53fd53-960a-4aa2-8b88-ad877ae089f2",
    title: "Automatic Motor Gas Motorcycles",
    description:
      "150cc 4-Stroke Motorcycle Automatic Motor Gas Motorcycles Scooter motorcycles 150cc scooter",
    price: 1050,
    discountPercentage: 40.77834179357022,
    rating: 4.84,
    stock: 127,
    brand: "shock absorber",
    category: "automotivevehicle",
    thumbnail: "https://i.dummyjson.com/data/products/93/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/93/1.jpg",
      "https://i.dummyjson.com/data/products/93/2.jpg",
      "https://i.dummyjson.com/data/products/93/3.jpg",
      "https://i.dummyjson.com/data/products/93/4.jpg",
      "https://i.dummyjson.com/data/products/93/thumbnail.jpg",
    ],
    trending: false,
    MRP: 1773,
    in_stock: true,
  },
  {
    _id: "1342eec7-d75b-4d61-9350-2f708d425b8e",
    title: "new arrivals Fashion motocross goggles",
    description:
      "new arrivals Fashion motocross goggles motorcycle motocross racing motorcycle",
    price: 900,
    discountPercentage: 43.75,
    rating: 4.06,
    stock: 109,
    brand: "JIEPOLLY",
    category: "automotivevehicle",
    thumbnail: "https://i.dummyjson.com/data/products/94/thumbnail.webp",
    images: [
      "https://i.dummyjson.com/data/products/94/1.webp",
      "https://i.dummyjson.com/data/products/94/2.jpg",
      "https://i.dummyjson.com/data/products/94/3.jpg",
      "https://i.dummyjson.com/data/products/94/thumbnail.webp",
    ],
    trending: false,
    MRP: 1600,
    in_stock: true,
  },
  {
    _id: "e1ecc158-262a-464e-9453-0e6cf5d6acc4",
    title: "Wholesale cargo lashing Belt",
    description:
      "Wholesale cargo lashing Belt Tie Down end Ratchet strap customized strap 25mm motorcycle 1500kgs with rubber handle",
    price: 930,
    discountPercentage: 42.944785276073624,
    rating: 3.21,
    stock: 144,
    brand: "Xiangle",
    category: "automotivevehicle",
    thumbnail: "https://i.dummyjson.com/data/products/95/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/95/1.jpg",
      "https://i.dummyjson.com/data/products/95/2.jpg",
      "https://i.dummyjson.com/data/products/95/3.jpg",
      "https://i.dummyjson.com/data/products/95/4.jpg",
      "https://i.dummyjson.com/data/products/95/thumbnail.jpg",
    ],
    trending: false,
    MRP: 1630,
    in_stock: true,
  },
  {
    _id: "aea7e896-204d-4827-80ad-2117b3573e50",
    title: "lighting ceiling kitchen",
    description:
      "Wholesale slim hanging decorative kid room lighting ceiling kitchen chandeliers pendant light modern",
    price: 30,
    discountPercentage: 71.69811320754717,
    rating: 3.83,
    stock: 96,
    brand: "lightingbrilliance",
    category: "home-appliances",
    thumbnail: "https://i.dummyjson.com/data/products/96/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/96/1.jpg",
      "https://i.dummyjson.com/data/products/96/2.jpg",
      "https://i.dummyjson.com/data/products/96/3.jpg",
      "https://i.dummyjson.com/data/products/96/4.jpg",
      "https://i.dummyjson.com/data/products/96/thumbnail.jpg",
    ],
    trending: true,
    MRP: 106,
    in_stock: true,
  },
  {
    _id: "157d331e-54bd-41b5-b09c-20439df60056",
    title: "Metal Ceramic Flower",
    description:
      "Metal Ceramic Flower Chandelier Home Lighting American Vintage Hanging Lighting Pendant Lamp",
    price: 35,
    discountPercentage: 0,
    rating: 2.93,
    stock: 146,
    brand: "Ifei Home",
    category: "home-appliances",
    thumbnail: "https://i.dummyjson.com/data/products/97/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/97/1.jpg",
      "https://i.dummyjson.com/data/products/97/2.jpg",
      "https://i.dummyjson.com/data/products/97/3.jpg",
      "https://i.dummyjson.com/data/products/97/4.webp",
      "https://i.dummyjson.com/data/products/97/thumbnail.jpg",
    ],
    trending: false,
    MRP: 35,
    in_stock: true,
  },
  {
    _id: "e700f116-a2f7-4b8e-939f-6a95b08f9157",
    title: "3 lights lndenpant kitchen islang",
    description:
      "3 lights lndenpant kitchen islang dining room pendant rice paper chandelier contemporary led pendant light modern chandelier",
    price: 34,
    discountPercentage: 0,
    rating: 3.99,
    stock: 44,
    brand: "DADAWU",
    category: "home-appliances",
    thumbnail: "https://i.dummyjson.com/data/products/98/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/98/1.jpg",
      "https://i.dummyjson.com/data/products/98/2.jpg",
      "https://i.dummyjson.com/data/products/98/3.jpg",
      "https://i.dummyjson.com/data/products/98/4.jpg",
      "https://i.dummyjson.com/data/products/98/thumbnail.jpg",
    ],
    trending: false,
    MRP: 34,
    in_stock: true,
  },
  {
    _id: "394b9304-aaad-41af-b6c5-4a804117275c",
    title: "American Vintage Wood Pendant Light",
    description:
      "American Vintage Wood Pendant Light Farmhouse Antique Hanging Lamp Lampara Colgante",
    price: 46,
    discountPercentage: 33.33333333333333,
    rating: 2.32,
    stock: 138,
    brand: "Ifei Home",
    category: "home-appliances",
    thumbnail: "https://i.dummyjson.com/data/products/99/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/99/1.jpg",
      "https://i.dummyjson.com/data/products/99/2.jpg",
      "https://i.dummyjson.com/data/products/99/3.jpg",
      "https://i.dummyjson.com/data/products/99/4.jpg",
      "https://i.dummyjson.com/data/products/99/thumbnail.jpg",
    ],
    trending: false,
    MRP: 69,
    in_stock: true,
  },
  {
    _id: "9ef18b0c-a8b3-4d06-b538-4d95bed55b97",
    title: "Crystal chandelier maria theresa for 12 light",
    description: "Crystal chandelier maria theresa for 12 light",
    price: 47,
    discountPercentage: 53,
    rating: 1.74,
    stock: 133,
    brand: "YIOSI",
    category: "home-appliances",
    thumbnail: "https://i.dummyjson.com/data/products/100/thumbnail.jpg",
    images: [
      "https://i.dummyjson.com/data/products/100/1.jpg",
      "https://i.dummyjson.com/data/products/100/2.jpg",
      "https://i.dummyjson.com/data/products/100/3.jpg",
      "https://i.dummyjson.com/data/products/100/thumbnail.jpg",
    ],
    trending: false,
    MRP: 100,
    in_stock: true,
  },
];
